// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJG98251Lpc7DAwF_q5tizqigzJYxbqik',
    appId: '1:71379184808:web:a4a0892a269c4ecc3ae69d',
    messagingSenderId: '71379184808',
    projectId: 'cleantogo-95163',
    authDomain: 'cleantogo-95163.firebaseapp.com',
    storageBucket: 'cleantogo-95163.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDym_3UEYBU1YTzgWq1tN7ZUXYdtNoDxm0',
    appId: '1:71379184808:android:31d896aac3d38ebe3ae69d',
    messagingSenderId: '71379184808',
    projectId: 'cleantogo-95163',
    storageBucket: 'cleantogo-95163.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjL5lpLZ9wMhuQs4470q4mSqG86375we0',
    appId: '1:71379184808:ios:c72ac667dceafb853ae69d',
    messagingSenderId: '71379184808',
    projectId: 'cleantogo-95163',
    storageBucket: 'cleantogo-95163.firebasestorage.app',
    iosBundleId: 'com.example.cleanTogo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjL5lpLZ9wMhuQs4470q4mSqG86375we0',
    appId: '1:71379184808:ios:c72ac667dceafb853ae69d',
    messagingSenderId: '71379184808',
    projectId: 'cleantogo-95163',
    storageBucket: 'cleantogo-95163.firebasestorage.app',
    iosBundleId: 'com.example.cleanTogo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJG98251Lpc7DAwF_q5tizqigzJYxbqik',
    appId: '1:71379184808:web:c861af1bd77527253ae69d',
    messagingSenderId: '71379184808',
    projectId: 'cleantogo-95163',
    authDomain: 'cleantogo-95163.firebaseapp.com',
    storageBucket: 'cleantogo-95163.firebasestorage.app',
  );
}
